name: lexo_rank
description: Implementation of LexoRank ordering of items in a list.
version: 0.1.0
repository: https://github.com/enzo-santos/lexo_rank.git

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  lints: ^5.1.0
  test: ^1.25.8
